/**
 * @author(Shubar, Abduelhakem G Abdusalam)
 * <p>
 * Load class is Model Class  updated by Controller class
 * -------------------------------------------------------
 * 1.  This class load all the key and sequence typed by user and generated by computer
 * 2.  This class load the file name base on the player name.
 */


import java.util.ArrayList;
import java.util.Scanner;

public class Load {

    private ArrayList<String> comSequence;
    private ArrayList<String> userSequence;
    private FileWriter writer;
    private File reader;
    private String fileName;
    private GameInterface gameInterface;

    /**
     * @author(Shubar, Abduelhakem G Abdusalam)
     * <p>
     * When the Load constructor is called.
     * a. Two ArrayList is create in order to store the loaded sequence.
     */
    public Load() {
        userSequence = new ArrayList<String>(18);
        comSequence = new ArrayList<String>(18);


    }

    /**
     * @author(Shubar, Abduelhakem G Abdusalam)
     * <p>
     * This function is use to load the computer sequences.
     */
    public ArrayList<String> getComSequence() {
        ArrayList<String> comSequenceContainer = new ArrayList<String>(18);
        for (String str : comSequence) {
            comSequenceContainer.add(str);
        }
        return comSequenceContainer;
    }

    /**
     * @author(Shubar, Abduelhakem G Abdusalam)
     * <p>
     * This function is use to load the user sequences.
     */
    public ArrayList<String> getUserSequence() {
        ArrayList<String> userSequenceContainer = new ArrayList<String>(18);
        for (String str : userSequence) {
            userSequenceContainer.add(str);
        }
        return userSequenceContainer;
    }


    /**
     * @author(Shubar, Abduelhakem G Abdusalam)
     * <p>
     * This function is use to open the file and get the sequences base on the player name
     */
    public void loading() {

        try {

            reader = new File(fileName + ".txt");
            Scanner scan = new Scanner(reader);

            for (int i = 0; i < 18; i++) {
                userSequence.add(scan.next());
            }

            for (int i = 0; i < 18; i++) {
                comSequence.add(scan.next());

            }

            scan.close();
           /* for(int i = 0; i < 18; i++){
            System.out.println(list.get(i));**/
        } catch (FileNotFoundException e) {

            if (!reader.exists()) {
                JOptionPane.showMessageDialog(null, "The system can't load the file, file does not exist.");
                System.exit(0);

            }

            if (reader.isDirectory()) {
                JOptionPane.showMessageDialog(null, "The system can't load the file, file is a directory.");
                System.exit(0);

            }

            if (!reader.canRead()) {
                JOptionPane.showMessageDialog(null, "The system can't read the file.");
                System.exit(0);

            }
        }
    }

    /**
     * @author(Shubar, Abduelhakem G Abdusalam)
     * <p>
     * This function is set filename base on player name
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public void setGameInterface(GameInterface gameInterface) {
        this.gameInterface = gameInterface;
    }


}


